#include<iostream>
#include<fstream>
#include<cstdio>
#include "TLeaf.h"
#include "TFile.h"
#include "TTree.h"
#include "TROOT.h"
#include "TString.h"
#include "TSystem.h"
#include <vector>
const int NMAX = 2000000;
int getExcludedQuartets(int *run, int *runlet, int *pattnum, int slug){
  int i = 0;
  ifstream file(Form("excluded_quartets/excluded_quartets_slug%i.txt", slug));
  if(!(file.good()&&file.is_open())){
    return -1;
  }
  string line;
  while(!file.eof()){
    file>>run[i]>>runlet[i]>>pattnum[i];
    //    cout<<pattnum[i]<<endl;
    getline(file,line);
    file.peek();
    ++i;
    if(i>=NMAX){
      cout<<"Exceeded maximum array length. Exiting.\n";
      return -1;
    }
  }
  return i;
}

void copyRegressedTree(TString filename, TString treename, 
		     TString friendfilename, TString friendname, int slugnum) {
  // Example of Root macro to copy a subset of a Tree to a new Tree
  // Only selected entries are copied to the new Tree.
  // The input file has been generated by the program in $ROOTSYS/test/Event
  // with   Event 1000 1 99 1
  //Author: Rene Brun

//   int exRun[NMAX], exRunlet[NMAX], exPattnum[NMAX];
//   int size = getExcludedQuartets(exRun, exRunlet, exPattnum, slugnum);
//   if(size<1)
//     return;
//   cout<<size<<" excluded quartets.\n";
  TFile *f = TFile::Open(Form("/net/data2/paschkelab2/missing_quartets/"
			      "reduced_slug%i_pattnum.root", slugnum));

  double exRun, exRunlet, exPattnum;  
  TTree *tr = (TTree*)f->Get("slug");
  if(f == 0){
    cout<<"Excluded quartets file not found. Exiting.\n";
  }
  if(tr->GetEntries() == 0){
    cout<<"No quartets to exclude. Exiting.\n";
    return;
  }
  tr->SetBranchAddress("run", &exRun);
  tr->SetBranchAddress("runlet", &exRunlet);
  tr->SetBranchAddress("pattnum", &exPattnum);
  //Get old file, old tree and set top branch address
  TString olddirname = "/net/data3/paschkelab4/pass5c_reduced_slugfiles/run2/too_many_entries";
  TFile *oldfile = new TFile(Form("%s/%s",olddirname.Data(), filename.Data()));
  TTree *oldtree = (TTree*)oldfile->Get(treename.Data());
  if(friendfilename.Length()>0)
    oldtree->AddFriend(friendname.Data(), Form("%s/%s", olddirname.Data(),
					       friendfilename.Data()));
  Long64_t nentries = oldtree->GetEntries();
  cout<<nentries<<" entries.\n";
  Int_t run, runlet;
  double pattnum;
  Float_t run_num = 0;

  if(oldtree->SetBranchAddress("run_number",&run)!=0)
    if(oldtree->SetBranchAddress("run",&run)!=0)
      oldtree->SetBranchAddress("run_number_decimal",&run_num);
  oldtree->SetBranchAddress("runlet", &runlet);
  oldtree->SetBranchAddress("pattnum", &pattnum);
  //Create a new file + a clone of old tree in new file
  TString newdirname = "/net/data3/paschkelab4/pass5c_reduced_slugfiles/run2";
  TString newfilename = filename;
  //  newfilename.Remove(newfilename.Length()-5,5);
  //  newfilename.Append("_trunc.root");
  TFile *newfile = new TFile(Form("%s/%s", newdirname.Data(), newfilename.Data()),
			     "recreate");
  TTree *newtree = oldtree->CloneTree(0);
  int nq = 0;
  tr->GetEntry(nq);
  for (Long64_t i=0;i<nentries; i++) {
    oldtree->GetEntry(i);
    if(i%100000==0)cout<<"Processing entry "<<i<<" of "<<nentries<<endl;
    if(run == exRun && runlet == exRunlet && (int)pattnum == exPattnum){
      cout<<"Excluding "<<exRun<<" "<<exRunlet<<" "<<exPattnum<<endl;
      ++nq;
      tr->GetEntry(nq);
    }else
      newtree->Fill();
  }
  newtree->Print();
  newtree->AutoSave();
  delete oldfile;
  delete newfile;
}
